/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvisosRouteImport } from './routes/avisos'
import { Route as ColaboradoresRouteImport } from './routes/colaboradores'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EsteiraRouteImport } from './routes/esteira'
import { Route as FaturamentoRouteImport } from './routes/faturamento'
import { Route as GargaloRouteImport } from './routes/gargalo'
import { Route as HorariosRouteImport } from './routes/horarios'
import { Route as MarcacaoProducaoRouteImport } from './routes/marcacao-producao'
import { Route as MarcacoesOrfasRouteImport } from './routes/marcacoes-orfas'
import { Route as MarcadoresRouteImport } from './routes/marcadores'
import { Route as OperacoesRouteImport } from './routes/operacoes'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as DashboardSetorSectorIdRouteImport } from './routes/dashboard-setor.$sectorId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisosRoute = AvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradoresRoute = ColaboradoresRouteImport.update({
  id: '/colaboradores',
  path: '/colaboradores',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EsteiraRoute = EsteiraRouteImport.update({
  id: '/esteira',
  path: '/esteira',
  getParentRoute: () => rootRouteImport,
} as any)
const FaturamentoRoute = FaturamentoRouteImport.update({
  id: '/faturamento',
  path: '/faturamento',
  getParentRoute: () => rootRouteImport,
} as any)
const GargaloRoute = GargaloRouteImport.update({
  id: '/gargalo',
  path: '/gargalo',
  getParentRoute: () => rootRouteImport,
} as any)
const HorariosRoute = HorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcacaoProducaoRoute = MarcacaoProducaoRouteImport.update({
  id: '/marcacao-producao',
  path: '/marcacao-producao',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcacoesOrfasRoute = MarcacoesOrfasRouteImport.update({
  id: '/marcacoes-orfas',
  path: '/marcacoes-orfas',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcadoresRoute = MarcadoresRouteImport.update({
  id: '/marcadores',
  path: '/marcadores',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesRoute = OperacoesRouteImport.update({
  id: '/operacoes',
  path: '/operacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSetorSectorIdRoute = DashboardSetorSectorIdRouteImport.update({
  id: '/dashboard-setor/$sectorId',
  path: '/dashboard-setor/$sectorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avisos': typeof AvisosRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/dashboard': typeof DashboardRoute
  '/esteira': typeof EsteiraRoute
  '/faturamento': typeof FaturamentoRoute
  '/gargalo': typeof GargaloRoute
  '/horarios': typeof HorariosRoute
  '/marcacao-producao': typeof MarcacaoProducaoRoute
  '/marcacoes-orfas': typeof MarcacoesOrfasRoute
  '/marcadores': typeof MarcadoresRoute
  '/operacoes': typeof OperacoesRoute
  '/painel': typeof PainelRoute
  '/produtos': typeof ProdutosRoute
  '/dashboard-setor/$sectorId': typeof DashboardSetorSectorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avisos': typeof AvisosRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/dashboard': typeof DashboardRoute
  '/esteira': typeof EsteiraRoute
  '/faturamento': typeof FaturamentoRoute
  '/gargalo': typeof GargaloRoute
  '/horarios': typeof HorariosRoute
  '/marcacao-producao': typeof MarcacaoProducaoRoute
  '/marcacoes-orfas': typeof MarcacoesOrfasRoute
  '/marcadores': typeof MarcadoresRoute
  '/operacoes': typeof OperacoesRoute
  '/painel': typeof PainelRoute
  '/produtos': typeof ProdutosRoute
  '/dashboard-setor/$sectorId': typeof DashboardSetorSectorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/avisos': typeof AvisosRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/dashboard': typeof DashboardRoute
  '/esteira': typeof EsteiraRoute
  '/faturamento': typeof FaturamentoRoute
  '/gargalo': typeof GargaloRoute
  '/horarios': typeof HorariosRoute
  '/marcacao-producao': typeof MarcacaoProducaoRoute
  '/marcacoes-orfas': typeof MarcacoesOrfasRoute
  '/marcadores': typeof MarcadoresRoute
  '/operacoes': typeof OperacoesRoute
  '/painel': typeof PainelRoute
  '/produtos': typeof ProdutosRoute
  '/dashboard-setor/$sectorId': typeof DashboardSetorSectorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avisos'
    | '/colaboradores'
    | '/dashboard'
    | '/esteira'
    | '/faturamento'
    | '/gargalo'
    | '/horarios'
    | '/marcacao-producao'
    | '/marcacoes-orfas'
    | '/marcadores'
    | '/operacoes'
    | '/painel'
    | '/produtos'
    | '/dashboard-setor/$sectorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avisos'
    | '/colaboradores'
    | '/dashboard'
    | '/esteira'
    | '/faturamento'
    | '/gargalo'
    | '/horarios'
    | '/marcacao-producao'
    | '/marcacoes-orfas'
    | '/marcadores'
    | '/operacoes'
    | '/painel'
    | '/produtos'
    | '/dashboard-setor/$sectorId'
  id:
    | '__root__'
    | '/'
    | '/avisos'
    | '/colaboradores'
    | '/dashboard'
    | '/esteira'
    | '/faturamento'
    | '/gargalo'
    | '/horarios'
    | '/marcacao-producao'
    | '/marcacoes-orfas'
    | '/marcadores'
    | '/operacoes'
    | '/painel'
    | '/produtos'
    | '/dashboard-setor/$sectorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisosRoute: typeof AvisosRoute
  ColaboradoresRoute: typeof ColaboradoresRoute
  DashboardRoute: typeof DashboardRoute
  EsteiraRoute: typeof EsteiraRoute
  FaturamentoRoute: typeof FaturamentoRoute
  GargaloRoute: typeof GargaloRoute
  HorariosRoute: typeof HorariosRoute
  MarcacaoProducaoRoute: typeof MarcacaoProducaoRoute
  MarcacoesOrfasRoute: typeof MarcacoesOrfasRoute
  MarcadoresRoute: typeof MarcadoresRoute
  OperacoesRoute: typeof OperacoesRoute
  PainelRoute: typeof PainelRoute
  ProdutosRoute: typeof ProdutosRoute
  DashboardSetorSectorIdRoute: typeof DashboardSetorSectorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avisos': {
      id: '/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AvisosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaboradores': {
      id: '/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof ColaboradoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esteira': {
      id: '/esteira'
      path: '/esteira'
      fullPath: '/esteira'
      preLoaderRoute: typeof EsteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faturamento': {
      id: '/faturamento'
      path: '/faturamento'
      fullPath: '/faturamento'
      preLoaderRoute: typeof FaturamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gargalo': {
      id: '/gargalo'
      path: '/gargalo'
      fullPath: '/gargalo'
      preLoaderRoute: typeof GargaloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horarios': {
      id: '/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof HorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcacao-producao': {
      id: '/marcacao-producao'
      path: '/marcacao-producao'
      fullPath: '/marcacao-producao'
      preLoaderRoute: typeof MarcacaoProducaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcacoes-orfas': {
      id: '/marcacoes-orfas'
      path: '/marcacoes-orfas'
      fullPath: '/marcacoes-orfas'
      preLoaderRoute: typeof MarcacoesOrfasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcadores': {
      id: '/marcadores'
      path: '/marcadores'
      fullPath: '/marcadores'
      preLoaderRoute: typeof MarcadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes': {
      id: '/operacoes'
      path: '/operacoes'
      fullPath: '/operacoes'
      preLoaderRoute: typeof OperacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-setor/$sectorId': {
      id: '/dashboard-setor/$sectorId'
      path: '/dashboard-setor/$sectorId'
      fullPath: '/dashboard-setor/$sectorId'
      preLoaderRoute: typeof DashboardSetorSectorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisosRoute: AvisosRoute,
  ColaboradoresRoute: ColaboradoresRoute,
  DashboardRoute: DashboardRoute,
  EsteiraRoute: EsteiraRoute,
  FaturamentoRoute: FaturamentoRoute,
  GargaloRoute: GargaloRoute,
  HorariosRoute: HorariosRoute,
  MarcacaoProducaoRoute: MarcacaoProducaoRoute,
  MarcacoesOrfasRoute: MarcacoesOrfasRoute,
  MarcadoresRoute: MarcadoresRoute,
  OperacoesRoute: OperacoesRoute,
  PainelRoute: PainelRoute,
  ProdutosRoute: ProdutosRoute,
  DashboardSetorSectorIdRoute: DashboardSetorSectorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
