/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColaboradoresRouteImport } from './routes/colaboradores'
import { Route as HorariosRouteImport } from './routes/horarios'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ProdutosProductIdRouteImport } from './routes/produtos.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradoresRoute = ColaboradoresRouteImport.update({
  id: '/colaboradores',
  path: '/colaboradores',
  getParentRoute: () => rootRouteImport,
} as any)
const HorariosRoute = HorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosProductIdRoute = ProdutosProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProdutosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/horarios': typeof HorariosRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/produtos/$productId': typeof ProdutosProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/horarios': typeof HorariosRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/produtos/$productId': typeof ProdutosProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/horarios': typeof HorariosRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/produtos/$productId': typeof ProdutosProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/colaboradores' | '/horarios' | '/produtos' | '/produtos/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/colaboradores' | '/horarios' | '/produtos' | '/produtos/$productId'
  id:
    | '__root__'
    | '/'
    | '/colaboradores'
    | '/horarios'
    | '/produtos'
    | '/produtos/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColaboradoresRoute: typeof ColaboradoresRoute
  HorariosRoute: typeof HorariosRoute
  ProdutosRoute: typeof ProdutosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaboradores': {
      id: '/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof ColaboradoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horarios': {
      id: '/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof HorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/$productId': {
      id: '/produtos/$productId'
      path: '/$productId'
      fullPath: '/produtos/$productId'
      preLoaderRoute: typeof ProdutosProductIdRouteImport
      parentRoute: typeof ProdutosRoute
    }
  }
}

interface ProdutosRouteChildren {
  ProdutosProductIdRoute: typeof ProdutosProductIdRoute
}

const ProdutosRouteChildren: ProdutosRouteChildren = {
  ProdutosProductIdRoute: ProdutosProductIdRoute,
}

const ProdutosRouteWithChildren = ProdutosRoute._addFileChildren(
  ProdutosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColaboradoresRoute: ColaboradoresRoute,
  HorariosRoute: HorariosRoute,
  ProdutosRoute: ProdutosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
